"""Who preserved each fragment, as printed by Wharton (1908): a hand-made table.

Built by reading Wharton's note under every fragment (our hand pass, 2026-10-08). For each entry:
  authors  - the writers Wharton says quote (or adduce, or preserve) the fragment, first-named first;
  evidence - a short string copied from Wharton's note; tests check it occurs in the note (or, for "via", in the
             note of the fragment named, or for the Epigrams in Wharton's section introduction).
Names are given as Wharton writes them; CANON maps them to one name per writer and a rough kind.
Wharton reflects 1908 knowledge: many attributions are disputed today, and modern editions add papyri he never saw.
"""
from __future__ import annotations

# canonical name -> kind (our rough grouping, for colour in the network panel)
KINDS = {
    "Hephaestion": "metrician",
    "Attilius Fortunatianus": "metrician",
    "Marius Plotius": "metrician",
    "Apollonius Dyscolus": "grammarian or lexicon",
    "Herodian": "grammarian or lexicon",
    "Choeroboscus": "grammarian or lexicon",
    "Ammonius": "grammarian or lexicon",
    "Etymologicum Magnum": "grammarian or lexicon",
    "Pollux": "grammarian or lexicon",
    "Photius": "grammarian or lexicon",
    "Hesychius": "grammarian or lexicon",
    "Lexicon Seguerianum": "grammarian or lexicon",
    "Antiatticista": "grammarian or lexicon",
    "Phrynichus": "grammarian or lexicon",
    "Orion": "grammarian or lexicon",
    "Joannes Alexandrinus": "grammarian or lexicon",
    "Priscian": "grammarian or lexicon",
    "Cramer's Paris manuscripts": "grammarian or lexicon",
    "Scholiast on Pindar": "scholiast or commentator",
    "Scholiast on Aristophanes": "scholiast or commentator",
    "Scholiast on Apollonius Rhodius": "scholiast or commentator",
    "Scholiast on Sophocles": "scholiast or commentator",
    "Scholiast on Hermogenes": "scholiast or commentator",
    "Scholiast on Hesiod": "scholiast or commentator",
    "Scholiast on Homer": "scholiast or commentator",
    "Eustathius": "scholiast or commentator",
    "Servius": "scholiast or commentator",
    "Dionysius of Halicarnassus": "critic or rhetorician",
    "Longinus": "critic or rhetorician",
    "Demetrius": "critic or rhetorician",
    "Hermogenes": "critic or rhetorician",
    "Aristides": "critic or rhetorician",
    "Himerius": "critic or rhetorician",
    "Libanius": "critic or rhetorician",
    "Choricius": "critic or rhetorician",
    "Dio Chrysostom": "critic or rhetorician",
    "Maximus Tyrius": "critic or rhetorician",
    "Philostratus": "critic or rhetorician",
    "Julian": "critic or rhetorician",
    "Athenaeus": "anthology or miscellany",
    "Stobaeus": "anthology or miscellany",
    "Greek Anthology": "anthology or miscellany",
    "Aulus Gellius": "anthology or miscellany",
    "Zenobius": "anthology or miscellany",
    "proverb (many late authors)": "anthology or miscellany",
    "Aristotle": "philosopher",
    "Chrysippus": "philosopher",
    "Plutarch": "philosopher",
    "Strabo": "other",
    "Pausanias": "other",
    "Galen": "other",
    "Palaephatus": "other",
}

APOLL = "Apollonius Dyscolus"
EM = "Etymologicum Magnum"

# wharton_no -> (authors, evidence, via)
# via: None, an int (evidence is in that fragment's note), or "section" (Wharton's introduction to the Epigrams)
TABLE: dict[int, tuple[list[str], str, object]] = {
    1: (["Dionysius of Halicarnassus"], "Dionysius of Halicarnassus, writing at Rome about 25 B.C., quotes this", None),
    2: (["Longinus"], "Longinus, about 250 A.D., uses this", None),
    3: (["Eustathius"], "Quoted by Eustathius of Thessalonica", None),
    4: (["Hermogenes"], "Cited by Hermogenes", None),
    5: (["Athenaeus"], "quotes these verses", None),
    6: (["Strabo"], "From Strabo", None),
    7: ([APOLL], "Adduced by Apollonius of Alexandria", None),
    8: ([APOLL], "Adduced by Apollonius of Alexandria", None),
    9: ([APOLL], "From Apollonius", None),
    10: ([APOLL], "From Apollonius", None),
    11: (["Athenaeus"], "Quoted by Athenaeus", None),
    12: ([EM], "From the Etymologicum Magnum", None),
    13: ([APOLL], "From Apollonius", None),
    14: ([APOLL], "From Apollonius", None),
    15: ([APOLL], "From Apollonius", None),
    16: (["Scholiast on Pindar"], "the Scholiast quotes this fragment", None),
    17: ([EM], "From the Etymologicum Magnum", None),
    18: (["Ammonius"], "Quoted by Ammonius of Alexandria", None),
    19: (["Scholiast on Aristophanes", "Pollux"], "Quoted by the Scholiast on Aristophanes' Peace", None),
    20: (["Scholiast on Apollonius Rhodius"], "Quoted by the Scholiast on Apollonius of Rhodes", None),
    21: ([APOLL], "From Apollonius, as is also the following", None),
    22: ([APOLL], "From Apollonius, as is also the following", 21),
    23: ([APOLL], "Quoted by Apollonius, as is also the following fragment", None),
    24: ([APOLL], "Quoted by Apollonius, as is also the following fragment", 23),
    25: ([EM], "From the Etymologicum Magnum", None),
    26: (["Athenaeus"], "Athenaeus says", None),
    27: (["Plutarch"], "Quoted by Plutarch", None),
    28: (["Aristotle"], "Aristotle, in his Rhetoric, i. 9", None),
    29: (["Athenaeus"], "Athenaeus, speaking of the charm of lovers' eyes", None),
    30: (["Athenaeus"], "Quoted by Athenaeus", None),
    31: (["Athenaeus"], "Quoted by Athenaeus", None),
    32: (["Dio Chrysostom"], "Dio Chrysostom", None),
    33: (["Hephaestion"], "Quoted by Hephaestion", None),
    34: (["Plutarch"], "Quoted by Plutarch", None),
    35: (["Herodian"], "Preserved by Herodian", None),
    36: (["Chrysippus"], "Quoted by the Stoic philosopher Chrysippus", None),
    37: (["Herodian"], "Quoted by Herodian", None),
    38: ([EM], "Quoted in the Etymologicum Magnum", None),
    39: (["Scholiast on Sophocles"], "Quoted by the Scholiast on Sophocles", None),
    40: (["Hephaestion"], "Quoted by Hephaestion", None),
    41: (["Hephaestion"], "Quoted by Hephaestion together with fr. 40", None),
    42: (["Maximus Tyrius"], "Quoted by Maximus Tyrius", None),
    43: ([APOLL], "Quoted by Apollonius", None),
    44: (["Athenaeus"], "Quoted by Athenaeus", None),
    45: (["Hermogenes", "Eustathius"], "Quoted by Hermogenes and Eustathius", None),
    46: (["Athenaeus"], "From Athenaeus", None),
    47: (["Zenobius"], "Quoted as a proverb by Zenobius", None),
    48: (["Choeroboscus"], "Quoted by Choeroboscus", None),
    49: (["Athenaeus"], "Athenaeus says Sappho here mentions", None),
    50: (["Herodian"], "From Herodian", None),
    51: (["Athenaeus"], "quoted by Athenaeus", None),
    52: (["Hephaestion"], "Quoted by Hephaestion", None),
    53: (["Hephaestion"], "Quoted by Hephaestion", None),
    54: (["Hephaestion"], "Quoted by Hephaestion", None),
    55: (["Herodian"], "From Herodian", None),
    56: ([EM, "Athenaeus"], "From the Etymologicum Magnum, Athenaeus, and others", None),
    57: ([EM], "From the Etymologicum Magnum", None),
    58: (["Hephaestion"], "Quoted by Hephaestion together with the following", None),
    59: (["Hephaestion"], "Quoted by Hephaestion together with the following", 58),
    60: (["Hephaestion", "Attilius Fortunatianus", "Servius"], "Quoted by Hephaestion, Attilius Fortunatianus", None),
    61: (["Attilius Fortunatianus"], "From Attilius Fortunatianus", None),
    62: (["Hephaestion"], "Quoted by Hephaestion", None),
    63: (["Marius Plotius"], "From Marius Plotius", None),
    64: (["Pollux"], "Quoted by Pollux", None),
    65: ([], "", None),  # Wharton names no quoting author for the Greek line (gap)
    66: (["Priscian"], "From Priscian", None),
    67: (["Athenaeus"], "Quoted by Athenaeus", None),
    68: (["Stobaeus", "Plutarch"], "From Stobaeus", None),
    69: (["Chrysippus"], "Quoted by Chrysippus", None),
    70: (["Athenaeus"], "Athenaeus, speaking of the care", None),
    71: (["Choeroboscus"], "Quoted by Choeroboscus", None),
    72: ([EM], "Quoted in the Etymologicum Magnum", None),
    73: (["Scholiast on Aristophanes"], "Quoted by the Scholiast on Aristophanes", None),
    74: (["Maximus Tyrius"], "Quoted by Maximus Tyrius", None),
    75: (["Stobaeus", "Apostolius"], "From Stobaeus' Anthology, and Apostolius", None),
    76: (["Hephaestion"], "Quoted by Hephaestion", None),
    77: (["Hephaestion"], "Quoted by Hephaestion with the foregoing", None),
    78: (["Athenaeus"], "Athenaeus, quoting this fragment", None),
    79: (["Athenaeus"], "Athenaeus, quoting Clearchus", None),
    80: (["Herodian"], "Quoted by Herodian", None),
    81: (["Scholiast on Pindar"], "From the Scholiast on Pindar", None),
    82: (["Hephaestion"], "Quoted by Hephaestion", None),
    83: ([EM], "From the Etymologicum Magnum", None),
    84: (["Hephaestion"], "Quoted by Hephaestion", None),
    85: (["Hephaestion"], "Quoted and elaborately scanned by Hephaestion", None),
    86: (["Maximus Tyrius"], "From Maximus Tyrius", None),
    87: (["Hephaestion"], "From Hephaestion", None),
    88: (["Hephaestion"], "From Hephaestion", None),
    89: (["Pollux"], "From Pollux", None),
    90: (["Hephaestion"], "From Hephaestion", None),
    91: (["Hephaestion"], "Quoted by Hephaestion", None),
    92: (["Demetrius"], "Quoted by Demetrius", None),
    93: (["Scholiast on Hermogenes"], "Quoted by the Scholiast on Hermogenes", None),
    94: (["Demetrius"], "Quoted by Demetrius", None),
    95: ([EM, "Demetrius"], "From the Etymologicum Magnum", None),
    96: (["Cramer's Paris manuscripts"], "From a Parisian MS. edited by Cramer", None),
    97: (["Cramer's Paris manuscripts"], "From a Parisian MS. edited by Cramer", None),
    98: (["Hephaestion"], "From Hephaestion", None),
    99: (["Hephaestion"], "Quoted by Hephaestion", None),
    100: (["Choricius"], "an epithalamium by Choricius", None),
    101: (["Galen"], "Galen, the physician", None),
    102: ([APOLL, "Scholiast on Dionysius Thrax"], "Quoted by Apollonius, and by the Scholiast on Dionysius of Thrace", None),
    103: (["Hephaestion"], "From Hephaestion", None),
    104: (["Hephaestion"], "From Hephaestion", None),
    105: (["Servius"], "Quoted by Servius", None),
    106: (["Dionysius of Halicarnassus"], "From Dionysius of Halicarnassus", None),
    107: (["Marius Plotius"], "From Plotius", None),
    108: (["Marius Plotius"], "From Plotius", None),
    109: (["Demetrius"], "From Demetrius", None),
    110: (["Herodian"], "From a very corrupt passage in Herodian", None),
    111: ([APOLL], "From Apollonius", None),
    112: (["Athenaeus"], "From Athenaeus", None),
    113: (["proverb (many late authors)"], "A proverb quoted by many late authors", None),
    114: (["Scholiast on Apollonius Rhodius"], "Quoted by the Scholiast on Apollonius Rhodius", None),
    115: ([APOLL], "Quoted by Apollonius", None),
    116: (["Scholiast on Aristophanes"], "From the Scholiast on Aristophanes' Plutus", None),
    117: ([APOLL], "Quoted by Apollonius", None),
    118: (["Greek Anthology"], "All three are preserved only in the", "section"),
    119: (["Greek Anthology"], "All three are preserved only in the", "section"),
    120: (["Greek Anthology"], "All three are preserved only in the", "section"),
    121: (["Athenaeus"], "Athenaeus says", None),
    122: (["Demetrius"], "Quoted by Demetrius", None),
    123: (["Demetrius"], "Quoted by Demetrius", None),
    124: (["Demetrius"], "Demetrius says", None),
    125: (["Maximus Tyrius"], "Maximus Tyrius says", None),
    126: (["Julian"], "Quoted by Julian", None),
    127: (["Aristides"], "Aristides says", None),
    128: (["Pollux"], "Pollux writes", None),
    129: (["Philostratus"], "Philostratus says", None),
    130: (["Libanius"], "Libanius the rhetorician", None),
    131: (["Strabo"], "Strabo says", None),
    132: (["Scholiast on Apollonius Rhodius"], "The Scholiast on Apollonius Rhodius says", None),
    133: (["Himerius"], "Himerius says", None),
    134: (["Scholiast on Apollonius Rhodius"], "The Scholiast on Apollonius Rhodius says", None),
    135: (["Scholiast on Hesiod"], "The Scholiast on Hesiod", None),
    136: (["Maximus Tyrius"], "Maximus Tyrius says", None),
    137: (["Aristotle"], "Aristotle, in his Rhetoric, ii. 23", None),
    138: (["Athenaeus"], "Athenaeus says", None),
    139: (["Athenaeus"], "Athenaeus says", None),
    140: (["Palaephatus"], "says", None),
    141: ([], "", None),  # Wharton: "now appears as fr. 57A"
    142: (["Pausanias"], "Pausanias says", None),
    143: (["Aulus Gellius"], "Aulus Gellius", None),
    144: (["Servius"], "Servius, commenting on Vergil, Aeneid", None),
    145: (["Servius"], "Servius, commenting on Vergil, Eclog.", None),
    146: (["Philostratus"], "Philostratus says", None),
    147: (["Himerius"], "Himerius says", None),
    148: (["Eustathius"], "Eustathius says", None),
    149: (["Lexicon Seguerianum"], "The Lexicon Seguerianum defines", None),
    150: ([EM], "The Etymologicum Magnum defines", None),
    151: ([EM], "The Etymologicum Magnum says", None),
    152: ([APOLL], "Apollonius says", None),
    153: ([EM], "The Etymologicum Magnum says", None),
    154: (["Athenaeus"], "Athenaeus says", None),
    155: (["Pollux"], "Pollux says", None),
    156: (["Phrynichus"], "the grammarian, about 180 A.D., says", None),
    157: (["Hesychius"], "Hesychius, about 370 A.D., says", None),
    158: (["Cramer's Paris manuscripts"], "A Parisian MS. edited by Cramer says", None),
    159: (["Scholiast on Homer"], "A Scholiast on Homer quotes", None),
    160: (["Eustathius"], "Eustathius, commenting on the Iliad", None),
    161: (["Choeroboscus"], "Choeroboscus says", None),
    162: (["Joannes Alexandrinus"], "Joannes Alexandrinus", None),
    163: (["Antiatticista"], "in Antiatticista, says", None),
    164: (["Cramer's Paris manuscripts"], "A treatise on grammar edited by Cramer says", None),
    165: (["Phrynichus"], "Phrynichus says", None),
    166: (["Scholiast on Homer"], "A Scholiast on Homer, Iliad, iii. 219, says", None),
    167: (["Photius", "Scholiast on Theocritus"], "Photius, in his Lexicon", None),
    168: ([EM], "The Etymologicum Magnum says", None),
    169: (["Orion"], "Orion of Thebes, the grammarian", None),
    170: (["Pollux"], "Pollux says", None),
}

for extra in ("Apostolius", "Scholiast on Dionysius Thrax", "Scholiast on Theocritus"):
    KINDS.setdefault(extra, "anthology or miscellany" if extra == "Apostolius" else "scholiast or commentator")


def kind(author: str) -> str:
    return KINDS[author]
