"""Checks for build_data.py (educational demo, toy models; not research). Fast, standard library + pytest.

    python3 -m pytest -q tests          (from 2026/chemistry/page/)
"""
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

PAGE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PAGE))
import build_data as bd  # noqa: E402

FIX = PAGE / "tests" / "fixtures"
NODE = shutil.which("node")


def build_fixture_js(tmp_path):
    out = tmp_path / "data.js"
    data = bd.main(["--fixtures", "--out", str(out)])
    return data, out.read_text()


def test_fixture_build_is_labelled_placeholder(tmp_path):
    data, js = build_fixture_js(tmp_path)
    assert data["inputs"] == {"mirror_race": "fixture", "kagan_curve": "fixture", "soai_amplifier": "fixture"}
    assert data["preliminary"] and data["placeholder"]
    assert js.startswith("// Generated by build_data.py")
    assert "window.NOBEL_CHEM_DATA = " in js and "window.NOBEL_CHEM_KAGAN = " in js
    assert data["tag"] == "Educational demo, toy models. Not research."


def test_missing_inputs_do_not_crash(tmp_path, capsys):
    data = bd.main(["--from", str(tmp_path / "a"), str(tmp_path / "b"), str(tmp_path / "c"), "--out", str(tmp_path / "d.js")])
    assert data["inputs"] == {"mirror_race": "missing", "kagan_curve": "missing", "soai_amplifier": "missing"}
    assert data["mirror"] is None and data["kagan"] is None and data["amp"] is None and data["preliminary"]
    assert "missing" in capsys.readouterr().out
    assert "window.NOBEL_CHEM_KAGAN = null" in (tmp_path / "d.js").read_text()


def test_real_numbers_match_the_sources():
    # S03a / SCI p. 12; S03b / SCI p. 13; SV03; Nobel popular information (the pie)
    assert bd.SOAI_2003_PCT == [0.00005, 57, 99, 99.5]
    assert bd.REAL_RUNS["soai_2003"] | {} == {**bd.REAL_RUNS["soai_2003"], "runs": 37, "one": 19, "mirror": 18, "ee_range_pct": [15, 91]}
    assert (bd.REAL_RUNS["singleton_vo_2003"]["runs"], bd.REAL_RUNS["singleton_vo_2003"]["one"], bd.REAL_RUNS["singleton_vo_2003"]["mirror"]) == (54, 27, 27)
    assert bd.KAGAN_PIE == {"ligand": [75, 25], "catalysts_pct": [56.25, 37.5, 6.25], "effective": [90, 10], "ee_prod_pct": 80}
    # the pie is exact arithmetic: random pairs of a 3:1 mix, then the mixed pairs drop out
    a, b = 0.75, 0.25
    assert [a * a * 100, 2 * a * b * 100, b * b * 100] == bd.KAGAN_PIE["catalysts_pct"]
    assert a * a / (a * a + b * b) * 100 == 90 and (a * a - b * b) / (a * a + b * b) * 100 == 80


def test_no_unsourced_99_99_anywhere():
    for f in ("index.html", "build_data.py", "README.md"):
        p = PAGE / f
        if p.exists():
            assert "99.99" not in p.read_text(), f


def test_exact_binomial():
    assert bd.binom_two_sided(19, 37) == 1.0 and bd.binom_two_sided(27, 54) == 1.0
    assert bd.binom_two_sided(0, 10) == pytest.approx(2 / 1024)
    assert bd.binom_two_sided(2, 10) == pytest.approx(2 * (1 + 10 + 45) / 1024)
    assert bd.binom_two_sided(5000, 10000) == pytest.approx(1.0)
    # large-n branch agrees with the exact one near the switch
    lp = bd.binom_two_sided(1950, 4000)
    assert 0.1 < lp < 0.12  # z = -1.58 -> two-sided p ~ 0.114


def test_molecules_have_the_right_hands():
    one, mirror = bd.molecule("one"), bd.molecule("mirror")
    assert (one["cid"], one["cip"]) == (5950, "S")       # L-alanine is (S)
    assert (mirror["cid"], mirror["cip"]) == (71080, "R")  # D-alanine is (R)
    # PubChem's two conformers are mirror images through the z = 0 plane (heavy atoms within 0.05 A)
    for a, b in zip(one["atoms"], mirror["atoms"]):
        if a[0] != "H":
            assert a[0] == b[0] and abs(a[1] - b[1]) < 0.05 and abs(a[2] - b[2]) < 0.05 and abs(a[3] + b[3]) < 0.05


def test_cip_rule_on_a_hand_made_centre():
    # H straight back (-z); N at 12 o'clock, acid C at 4, methyl C at 8, seen from +z: clockwise -> R
    atoms = [{"el": "C", "x": 0, "y": 0, "z": 0}, {"el": "N", "x": 0, "y": 1, "z": .3},
             {"el": "C", "x": .87, "y": -.5, "z": .3}, {"el": "C", "x": -.87, "y": -.5, "z": .3},
             {"el": "H", "x": 0, "y": 0, "z": -1}, {"el": "O", "x": 1.7, "y": -.9, "z": .3}, {"el": "O", "x": .9, "y": -1.5, "z": .3},
             {"el": "H", "x": -1.7, "y": -.9, "z": .3}]
    bonds = [[0, 1, 1], [0, 2, 1], [0, 3, 1], [0, 4, 1], [2, 5, 2], [2, 6, 1], [3, 7, 1]]
    assert bd.cip_label(atoms, bonds) == "R"
    mirrored = [dict(a, x=-a["x"]) for a in atoms]
    assert bd.cip_label(mirrored, bonds) == "S"


def test_inline_kagan_handles_es_modules(tmp_path):
    (tmp_path / "kagan.js").write_text("export function eeProd(e, K, g) { return e; }\nexport const shares = (e, K) => [1, 0, 0];\n")
    js, names = bd.inline_kagan(tmp_path / "kagan.js")
    assert names == ["eeProd", "shares"] and "export function" not in js and "export const" not in js


@pytest.mark.skipif(NODE is None, reason="needs node")
def test_inlined_kagan_gives_the_exact_textbook_numbers(tmp_path):
    _, js = build_fixture_js(tmp_path)
    kag = js[js.index("window.NOBEL_CHEM_KAGAN"):]
    script = "var window = {};\n" + kag + """
    const K = window.NOBEL_CHEM_KAGAN, f = K.eeProd || K.ee_prod;
    const out = { pie: f(0.5, 4, 0), line: [0.1, 0.5, 0.9].map((x) => f(x, 4, 1)),
                  closed: [0.1, 0.3, 0.7].map((x) => f(x, 4, 0)), bigK: f(0.2, 1e9, 0) };
    console.log(JSON.stringify(out));"""
    r = subprocess.run([NODE, "-e", script], capture_output=True, text=True, timeout=30)
    assert r.returncode == 0, r.stderr
    o = json.loads(r.stdout)
    assert o["pie"] == pytest.approx(0.8, abs=1e-12)                        # 75:25 -> 80 %
    assert o["line"] == pytest.approx([0.1, 0.5, 0.9], abs=1e-12)          # g = 1: straight line
    assert o["closed"] == pytest.approx([2 * x / (1 + x * x) for x in (0.1, 0.3, 0.7)], abs=1e-12)  # K = 4, g = 0
    assert o["bigK"] == pytest.approx(1.0, abs=1e-3)                        # K -> infinity, g = 0: ee_max


def test_race_rates_default_to_the_mirror_race_constants(tmp_path):
    data, _ = build_fixture_js(tmp_path)
    assert data["race_rates"]["k0"] == 1 and data["race_rates"]["k1"] == 1 and data["race_rates"]["k2"] == 100
    assert data["race_N"] == 2000


def test_histograms_and_runs_are_normalised(tmp_path):
    data, _ = build_fixture_js(tmp_path)
    h = data["mirror"]["hist"]
    assert len(h["edges"]) == len(h["copy_only"]) + 1 == 42
    assert math.isclose(sum(h["with_antagonism"]), 10000)
    assert data["mirror"]["race_runs"]["copy_only"][0]["one"][0] == 0
