"""Which LSJ headword each Greek word of Wharton's text belongs to (our lemmatisation, by hand).

Keys are Perseus LSJ entry keys (beta code). Where LSJ itself cites this poem (as "Sapph. 2.<line>", Bergk's numbering,
the same as Wharton's), the entry is marked "cites_this_line": the tests check that the citation is in the stored
entry. Aeolic forms are glossed under the Attic headword LSJ uses; "form_note" says so.
"""
LEMMA = {
    "greek:1:1": ("fai/nw", None),
    "greek:1:2": ("e)gw/", "dative of ἐγώ, 'I'"),
    "greek:1:3": ("kh=nos", "Aeolic for ἐκεῖνος, 'that one'"),
    "greek:1:4": ("i)/sos", None),
    "greek:1:5": ("qeo/s", "Aeolic dative plural"),
    "greek:2:1": ("ei)mi/1", "Aeolic infinitive of εἰμί"),
    "greek:2:2": ("a)nh/r", "crasis of ὁ ἀνήρ, 'the man'"),
    "greek:2:3": ("o(/stis", None),
    "greek:2:4": ("e)nanti/os", None),
    "greek:2:5": ("su/", "Aeolic dative of σύ, 'you'"),
    "greek:3:1": ("i(za/nw", None),
    "greek:3:2": ("kai/1", None),
    "greek:3:3": ("plhsi/os", "Aeolic πλάσιον for πλησίον, adverb"),
    "greek:3:4": ("h(du/s", "Aeolic ἆδυ for ἡδύ, neuter used as adverb"),
    "greek:3:5": ("fwne/w", "Aeolic participle, feminine"),
    "greek:4:1": ("u(pakou/w", None),
    "greek:5:1": ("kai/1", None),
    "greek:5:2": ("gela/w", "Aeolic participle, feminine"),
    "greek:5:3": ("i(mero/eis", "neuter used as adverb"),
    "greek:5:4": ("o(1", "article used as a pronoun, 'that'"),
    "greek:5:5": ("e)gw/", "dative of ἐγώ"),
    "greek:5:6": ("ma/n", "Aeolic/Doric for μήν"),
    "greek:6:1": ("kardi/a", None),
    "greek:6:2": ("e)n", None),
    "greek:6:3": ("sth=qos", None),
    "greek:6:4": ("ptoe/w", None),
    "greek:7:1": ("w(s", None),
    "greek:7:2": ("ga/r", None),
    "greek:7:3": ("ei)/dw1", "Aeolic form of εἶδον (aorist of 'see')"),
    "greek:7:4": ("bro/xus", "Aeolic for βραχύς; adverb"),
    "greek:7:5": ("su/", "accusative of σύ"),
    "greek:7:6": ("fwnh/", None),
    "greek:8:1": ("ou)dei/s", None),
    "greek:8:2": ("e)/ti", None),
    "greek:8:3": ("ei)/kw2", None),
    "greek:9:1": ("a)lla/", None),
    "greek:9:2": ("kata/1", "κάτ before μ (κὰμ), split from its verb (κατέαγε)"),
    "greek:9:3": ("me/n", None),
    "greek:9:4": ("glw=ssa", None),
    "greek:9:5": ("a)/gnumi", "with κὰμ: κατέαγε, 'is broken'"),
    "greek:9:6": ("lepto/s", None),
    "greek:9:7": ("de/1", None),
    "greek:10:1": ("au)ti/ka^", None),
    "greek:10:2": ("xrw/s", None),
    "greek:10:3": ("pu=r", None),
    "greek:10:4": ("u(potre/xw", "Aeolic perfect"),
    "greek:11:1": ("o)ppa/tessi", "Aeolic dative plural of ὄμμα"),
    "greek:11:2": ("de/1", None),
    "greek:11:3": ("ou)dei/s", None),
    "greek:11:4": ("o)/rhmi", "Aeolic for ὁράω"),
    "greek:11:5": ("e)pirrombe/w", None),
    "greek:12:1": ("de/1", None),
    "greek:12:2": ("a)koh/", "Aeolic ἄκουα for ἀκοή"),
    "greek:13:1": ("o(1", "Aeolic ἀ (ἁ) for ἡ, the article"),
    "greek:13:2": ("de/1", None),
    "greek:13:3": ("i(drw/s", "as printed by Wharton, μίδρως = μ' ἴδρως, 'sweat ... me'"),
    "greek:13:4": ("kataxe/w", "Aeolic κακχέεται for καταχεῖται"),
    "greek:13:5": ("tro/mos1", None),
    "greek:13:6": ("de/1", None),
    "greek:14:1": ("pa=s1", "Aeolic παῖσαν for πᾶσαν"),
    "greek:14:2": ("a)gre/w", "Aeolic"),
    "greek:14:3": ("xlwro/s", "comparative"),
    "greek:14:4": ("de/1", None),
    "greek:14:5": ("poi/a", "Ionic/Aeolic for πόα"),
    "greek:15:1": ("ei)mi/1", "Aeolic first person ἔμμι for εἰμί"),
    "greek:15:2": ("qnh/|skw", "Aeolic perfect infinitive"),
    "greek:15:3": ("de/1", None),
    "greek:15:4": ("o)li/gos", "Aeolic genitive"),
    "greek:15:5": ("e)pideuh/s", None),
    "greek:16:1": ("fai/nw", None),
    "greek:16:2": ("a)/llos1", "in square brackets in Wharton's text: an editor's supplement"),
}
