"""Checks of build_data.py, data.js and index.html. Educational demos made to show an open-source tool. Not research.

    python3 -m pytest -q tests      (from 2026/peace/page/)
"""
import ast
import codecs
import json
import re
import sys
from pathlib import Path

import pytest

PAGE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PAGE))
import build_data  # noqa: E402

FIX = PAGE / "tests" / "fixtures"
ENDS, HOLD = (FIX / t / "results" for t in build_data.TOYS)
HTML = (PAGE / "index.html").read_text(encoding="utf-8")
# the terms are stored in rot13 so that no file of the page spells them
EXCLUDED = re.compile(codecs.decode("tnmn|vfenry|cnyrfgva", "rot13"), re.I)
# countries and regions that appear most in the UCDP lists (rot13); the page is global totals only, so none should appear
COUNTRIES = tuple(codecs.decode(c, "rot13") for c in (
    "Nstunavfgna", "Nytrevn", "Natbyn", "Nezravn", "Nmreonvwna", "Ohehaqv", "Pnzobqvn", "Punq", "Pbybzovn", "Pbatb",
    "Rguvbcvn", "Revgern", "Trbetvn", "Thngrznyn", "Vaqvn", "Vaqbarfvn", "Vena", "Vend", "Yronaba", "Yvorevn",
    "Yvoln", "Znyv", "Zbmnzovdhr", "Zlnazne", "Arcny", "Avtrevn", "Cnxvfgna", "Cuvyvccvarf", "Ehffvn", "Ejnaqn",
    "Fvreen Yrbar", "Fbznyvn", "Fev Ynaxn", "Fhqna", "Flevn", "Gnwvxvfgna", "Ghexrl", "Htnaqn", "Hxenvar", "Lrzra",
    "Xbfbib", "Obfavn", "Pebngvn", "Xnfuzve", "Purpualn", "Qneshe", "Zvaqnanb"))


def read_js(path):
    s = Path(path).read_text(encoding="utf-8")
    return s, json.loads(s[s.index("= ") + 2:s.rstrip().rindex(";")])


def fixture_json(i):
    return json.loads((FIX / build_data.TOYS[i] / "results" / build_data.FILES[i]).read_text(encoding="utf-8"))


def test_fixtures_are_labelled(tmp_path):
    d = build_data.main(["--fixtures", "--out", str(tmp_path / "d.js")])
    assert d["placeholder"] and d["preliminary"]
    assert set(d["inputs"].values()) == {"fixture"}


def test_missing_inputs_do_not_crash(tmp_path):
    d = build_data.main(["--from", str(tmp_path / "a"), str(tmp_path / "b"), "--out", str(tmp_path / "d.js")])
    assert d["ends"] is None and d["hold"] is None and set(d["inputs"].values()) == {"missing"} and d["preliminary"]
    assert "not in this copy" in HTML


def test_status_rules():
    assert build_data.status_of(None) == "missing"
    assert build_data.status_of({}) == "final"
    assert build_data.status_of({"status": "final (v2)"}) == "final"
    assert build_data.status_of({"status": "draft"}) == "preliminary"


def test_headline_numbers():
    d = build_data.build(ENDS, HOLD)
    E, H = d["ends"], d["hold"]
    assert (E["pct"], E["agree"], E["endings"], E["years"]) == (25.0, 127, 507, [1946, 2023])
    assert (E["second"]["low_activity_first_decade_pct"], E["second"]["low_activity_2010s_pct"]) == (17.4, 65.0)
    assert (E["second"]["complete_decades_since_1990_min_pct"], E["second"]["before_1990_max_pct"]) == (61.0, 38.5)
    assert sum(x["n"] for x in E["decades"]) == E["endings"] and sum(x["agree"] for x in E["decades"]) == E["agree"]
    assert (H["main"]["pct"], H["main"]["ci"], H["strict"]["pct"], H["horizon"]) == (52.3, [37.4, 68.1], 31.5, 5)
    assert H["main"]["reached"] + H["main"]["never"] == H["agreements"] == 374
    assert H["groups"] == 72 and H["main"]["logrank"]["three_types_p"] > 0.05
    for k in ("main", "strict"):
        c = H[k]["curve"]
        assert c[0] == [0, 1.0] and all(a[1] >= b[1] for a, b in zip(c, c[1:])) and c[-1][0] <= H["figure_years"]


def test_numbers_match_the_toys_json():
    e, h = fixture_json(0), fixture_json(1)
    d = build_data.build(ENDS, HOLD)
    E, H = d["ends"], d["hold"]
    for p, x in zip(e["by_decade"], E["decades"]):
        assert (x["pct"], x["low"], x["clear_pct"], x["ci"]) == (p["agreement_or_ceasefire_pct"], p["low_activity_pct"],
                                                                 p["agreement_or_ceasefire_among_clear_pct"], p["agreement_or_ceasefire_ci95_pct"])
    assert E["trends"]["clear"]["slope_ci95"] == e["trends"]["agreement_or_ceasefire_among_clear_outcomes"]["slope_ci95"]
    a = h["main"]["groups"]["All"]
    assert H["main"]["pct"] == a["holding_at_5_years_pct"] and H["main"]["ci"] == a["holding_at_5_years_cluster_ci95_pct"]
    assert H["main"]["curve"] == [[c["t"], c["S"]] for c in a["curve"] if c["t"] <= h["definition"]["figure_years"]]
    assert H["strict"]["both_active"] == h["strict"]["next_year_and_signing_year_both_active"]


def test_committed_data_js_is_the_final_toys():
    s, d = read_js(PAGE / "data.js")
    assert s.startswith("// Generated by build_data.py; do not edit. " + build_data.TAG)
    assert d["tag"] == build_data.TAG and not d["preliminary"] and set(d["inputs"].values()) == {"final"}
    f = build_data.build(ENDS, HOLD)
    assert d["ends"] == f["ends"] and d["hold"] == f["hold"] and d["prize"] == f["prize"]
    assert len(s.encode()) < 30_000


def test_exact_citations_and_credits():
    e, h = fixture_json(0), fixture_json(1)
    d = build_data.build(ENDS, HOLD)
    assert d["ends"]["credit"]["citation"] == e["dataset"]["citation"]
    assert d["hold"]["credit"]["pa"]["citation"] == h["datasets"]["peace_agreements"]["citation"]
    assert d["hold"]["credit"]["pa"]["codebook_citation"] == h["datasets"]["peace_agreements"]["codebook_citation"]
    assert d["ends"]["credit"]["licence"] == h["datasets"]["licence"] == "CC BY 4.0"
    assert d["prize"]["laureate"] in e["prize"] and d["prize"]["citation"] in e["prize"] and e["prize"] == h["prize"]
    assert d["prize"]["url"] == "https://www.nobelprize.org/prizes/peace/2026/press-release/"


def test_narrator_sentences_are_the_toys_insights():
    d = build_data.build(ENDS, HOLD)
    for blk, toy in ((d["ends"], build_data.TOYS[0]), (d["hold"], build_data.TOYS[1])):
        md = (FIX / toy / "INSIGHTS.md").read_text(encoding="utf-8")
        assert len(blk["insights"]) == 5 and all(i["text"] in md and i["fields"] for i in blk["insights"])


def _body_text(html):
    body = html[html.index("<body>"):]
    body = re.sub(r"<(script|style)\b.*?</\1>", " ", body, flags=re.S)
    return re.sub(r"<[^>]+>", " ", body)


def _js_strings(html):
    js = " ".join(re.findall(r"<script>(.*?)</script>", html, flags=re.S))
    js = re.sub(r"\\u[0-9a-fA-F]{4}", "", js)
    js = re.sub(r"\$\{[^}]*\}", "", js)
    js = re.sub(r"^\s*//.*$", "", js, flags=re.M)
    return [m.group(0) for m in re.finditer(r"([\"'`])(?:\\.|(?!\1)[^\\\n])*\1", js)]


def test_no_number_is_typed_into_index_html():
    assert not re.search(r"\d", _body_text(HTML)), re.findall(r".{20}\d.{20}", _body_text(HTML))
    bad = [s for s in _js_strings(HTML) if re.search(r"\d", s) and not re.match(r"[\"'`]https?://", s)]
    assert not bad, bad
    head = HTML[:HTML.index("</head>")]
    texts = re.findall(r"<title>(.*?)</title>", head) + re.findall(r'name="description" content="([^"]*)"', head)
    texts += re.findall(r'property="og:(?:title|description|image:alt)" content="([^"]*)"', head)
    assert all(set(re.findall(r"\d+", t)) <= {"2026"} for t in texts)


def test_no_names_and_no_excluded_places():
    for p in PAGE.rglob("*"):
        if p.is_file() and p.suffix in (".html", ".js", ".md", ".py", ".mjs", ".txt", ".json"):
            t = p.read_text(encoding="utf-8")
            assert not EXCLUDED.search(t), p
            hits = [c for c in COUNTRIES if re.search(r"\b" + c + r"\b", t)]
            assert not hits, (p, hits)


def test_build_data_is_stdlib_only():
    tree = ast.parse((PAGE / "build_data.py").read_text(encoding="utf-8"))
    mods = {a.name.split(".")[0] for n in ast.walk(tree) if isinstance(n, ast.Import) for a in n.names}
    mods |= {n.module.split(".")[0] for n in ast.walk(tree) if isinstance(n, ast.ImportFrom)}
    assert mods <= set(sys.stdlib_module_names), mods


def test_bundled_fonts_cover_the_page():
    for f in ("sans", "sans-bold", "serif", "italic"):
        assert (PAGE / "fonts" / f"{f}.woff2").exists()
    assert "SIL Open Font License" in (PAGE / "fonts" / "OFL.txt").read_text(encoding="utf-8")
    TTFont = pytest.importorskip("fontTools.ttLib").TTFont
    pytest.importorskip("brotli")
    _, d = read_js(PAGE / "data.js")
    chars = set(re.sub(r"<[^>]+>", "", _body_text(HTML)) + "".join(_js_strings(HTML)) + json.dumps(d, ensure_ascii=False))
    chars |= set("0123456789.,%\u00a0\u2212\u201c\u201d\u2019")
    cmap = set(TTFont(str(PAGE / "fonts" / "sans.woff2")).getBestCmap())
    missing = {c for c in chars if c.isprintable() and not c.isspace() and ord(c) not in cmap}
    assert not missing, sorted(missing)


def test_og_and_screenshots():
    Image = pytest.importorskip("PIL.Image")
    assert Image.open(PAGE / "og.jpg").size == (1200, 630)
    for w in (360, 768, 1440):
        for t in ("light", "dark"):
            assert Image.open(PAGE / "screenshots" / f"page_{w}_{t}.png").size[0] == w
