#!/usr/bin/env python3
"""Build event.js for the Glashow-event replay page from IceCube's public event file (stdlib only).

The input is `event.txt` from the IceCube data release "IceCube detection of a high-energy particle
shower at the Glashow resonance" (DOI 10.21234/gr2021, https://doi.org/10.21234/gr2021). Download the
release from that DOI and pass the path of its event.txt; the page itself only needs event.js.

    python3 build_data.py path/to/event.txt            # writes event.js next to this script
    python3 build_data.py path/to/event.txt --out other.js

event.txt has four "## " sections; this script uses two of them:
  "## Extracted pulses"  string, om, time [ns], charge [pe]   (one row per light pulse)
  "## Geometry"          string, om, x, y, z [m], rel_dom_eff (IceCube coordinates, z up)
Only the in-ice sensors are kept: strings 1-86, om 1-60 (86 x 60 = 5,160 sensors).

event.js sets window.GLASHOW with:
  sx, sy      x and y of each string [m, 0.1 m]          (index = string - 1)
  z           z of every sensor [m, 0.1 m]               (index = (string - 1) * 60 + om - 1)
  hits        per hit sensor: [sensor index, first-hit time [ns], total charge [pe], pulses]
  pulses      every pulse sorted by time, flattened: sensor index, time [ns], charge [pe], ...
Times are in ns since the first pulse of the event (t0, the original time, is stored too).
"""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
N_STRINGS, N_OM = 86, 60
SURFACE_Z = 1948.07  # ice surface in IceCube coordinates [m]: depth = SURFACE_Z - z


def sections(text):
    out, name = {}, None
    for line in text.splitlines():
        if line.startswith("## "):
            name = line[3:].strip()
            out[name] = []
        elif name and line.strip() and not line.startswith("#"):
            out[name].append(line.split())
    return out


def r1(x):
    v = round(x, 1)
    return int(v) if v == int(v) else v


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("event_txt", type=Path)
    ap.add_argument("--out", type=Path, default=HERE / "event.js")
    args = ap.parse_args()
    sec = sections(args.event_txt.read_text(encoding="utf-8"))

    geo = {}
    for s, om, x, y, z, *_ in sec["Geometry"]:
        s, om = int(s), int(om)
        if 1 <= s <= N_STRINGS and 1 <= om <= N_OM:
            geo[(s, om)] = (float(x), float(y), float(z))
    assert len(geo) == N_STRINGS * N_OM, len(geo)
    sx = [r1(geo[(s, 1)][0]) for s in range(1, N_STRINGS + 1)]
    sy = [r1(geo[(s, 1)][1]) for s in range(1, N_STRINGS + 1)]
    zs = [r1(geo[(s, om)][2]) for s in range(1, N_STRINGS + 1) for om in range(1, N_OM + 1)]

    raw = [(int(s), int(om), float(t), float(q)) for s, om, t, q in sec["Extracted pulses"]]
    assert all((s, om) in geo for s, om, _, _ in raw), "pulse on a sensor outside the in-ice set"
    raw.sort(key=lambda p: p[2])
    t0 = raw[0][2]
    idx = lambda s, om: (s - 1) * N_OM + om - 1
    pulses, hits = [], {}
    for s, om, t, q in raw:
        i, dt = idx(s, om), t - t0
        pulses += [i, r1(dt), float(f"{q:.3g}")]
        h = hits.setdefault(i, [i, r1(dt), 0.0, 0])
        h[2] += q
        h[3] += 1
    hit_list = sorted(hits.values(), key=lambda h: h[1])
    for h in hit_list:
        h[2] = float(f"{h[2]:.4g}")
    firsts = sorted(h[1] for h in hit_list)

    data = {
        "source": "IceCube Collaboration, DOI 10.21234/gr2021 (event.txt, Extracted pulses + Geometry)",
        "t0_ns": round(t0, 3),
        "surface_z": SURFACE_Z,
        "n_pulses": len(raw),
        "n_hit": len(hit_list),
        "n_sensors": len(geo),
        "total_pe": round(sum(p[3] for p in raw)),
        "t_end": r1(raw[-1][2] - t0),
        "first_hit_p95": firsts[int(0.95 * (len(firsts) - 1))],
        "sx": sx, "sy": sy, "z": zs,
        "hits": hit_list,
        "pulses": pulses,
    }
    js = ("// Generated by build_data.py from IceCube's public event file (DOI 10.21234/gr2021). Do not edit.\n"
          "window.GLASHOW = " + json.dumps(data, separators=(",", ":")) + ";\n")
    args.out.write_text(js, encoding="utf-8")
    print(f"wrote {args.out.name}: {len(js) / 1024:.0f} KB; {len(geo)} sensors, {len(hit_list)} hit, "
          f"{len(raw)} pulses over {data['t_end']} ns, {data['total_pe']} pe")


if __name__ == "__main__":
    main()
